<?php

namespace Kubus\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LessonToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonToolRepository extends EntityRepository
{
}
