<?php

namespace Kubus\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScienceDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScienceDomainRepository extends EntityRepository
{
}
