parameters:
#    kubus_manager.example.class: Kubus\ManagerBundle\Example

services:
#    kubus_manager.example:
#        class: %kubus_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
