kubus_backend:
    resource: "@KubusBackendBundle/Resources/config/routing.yml"
    prefix:   /backend/

kubus_frontend:
    resource: "@KubusFrontendBundle/Resources/config/routing.yml"
    prefix:   /
