parameters:
#    kubus_admin.example.class: Kubus\AdminBundle\Example

services:
#    kubus_admin.example:
#        class: %kubus_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
