parameters:
#    kubus_user.example.class: Kubus\UserBundle\Example

services:
#    kubus_user.example:
#        class: %kubus_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
