manager:
    pattern:  /
    defaults: { _controller: "KubusBackendBundle:Manager:index" }

manager_show:
    pattern:  /{id}/show
    defaults: { _controller: "KubusBackendBundle:Manager:show" }

manager_new:
    pattern:  /new
    defaults: { _controller: "KubusBackendBundle:Manager:new" }

manager_create:
    pattern:  /create
    defaults: { _controller: "KubusBackendBundle:Manager:create" }
    requirements: { _method: post }

manager_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KubusBackendBundle:Manager:edit" }

manager_update:
    pattern:  /{id}/update
    defaults: { _controller: "KubusBackendBundle:Manager:update" }
    requirements: { _method: post|put }

manager_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KubusBackendBundle:Manager:delete" }
    requirements: { _method: post|delete }
