message:
    pattern:  /
    defaults: { _controller: "KubusBackendBundle:Message:index" }

message_show:
    pattern:  /{id}/show
    defaults: { _controller: "KubusBackendBundle:Message:show" }

message_new:
    pattern:  /new
    defaults: { _controller: "KubusBackendBundle:Message:new" }

message_create:
    pattern:  /create
    defaults: { _controller: "KubusBackendBundle:Message:create" }
    requirements: { _method: post }

message_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KubusBackendBundle:Message:edit" }

message_update:
    pattern:  /{id}/update
    defaults: { _controller: "KubusBackendBundle:Message:update" }
    requirements: { _method: post|put }

message_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KubusBackendBundle:Message:delete" }
    requirements: { _method: post|delete }
